// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnCallApi.Data;

#nullable disable

namespace OnCallApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726184703_AddMultiTenantSupport")]
    partial class AddMultiTenantSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnCallApi.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Key");

                    b.HasIndex("TenantId");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("OnCallApi.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OnCallApi.Models.CodeCallLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Zone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("CodeCallLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1314),
                            IsActive = true,
                            Name = "3 West — Room 312",
                            Zone = "3-west"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1317),
                            IsActive = true,
                            Name = "ICU — Bay 4",
                            Zone = "icu"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1318),
                            IsActive = true,
                            Name = "Emergency Dept — Trauma 2",
                            Zone = "ed"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1319),
                            IsActive = true,
                            Name = "Main Lobby",
                            Zone = "lobby"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1320),
                            IsActive = true,
                            Name = "Radiology — MRI Suite",
                            Zone = "radiology"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1321),
                            IsActive = true,
                            Name = "Labor & Delivery — Room 8",
                            Zone = "ld"
                        });
                });

            modelBuilder.Entity("OnCallApi.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureAdGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Healthcare",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1837),
                            Description = "Emergency Department",
                            IsActive = true,
                            Name = "Emergency Medicine",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Healthcare",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1843),
                            Description = "Heart & Vascular",
                            IsActive = true,
                            Name = "Cardiology",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Healthcare",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1846),
                            Description = "General Medicine",
                            IsActive = true,
                            Name = "Internal Medicine",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Healthcare",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1847),
                            Description = "Children's Health",
                            IsActive = true,
                            Name = "Pediatrics",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Healthcare",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1849),
                            Description = "Surgical Services",
                            IsActive = true,
                            Name = "Surgery",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Healthcare",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1850),
                            Description = "Hospital Administration",
                            IsActive = true,
                            Name = "Administration",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Technology",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1852),
                            Description = "IT Infrastructure & Support",
                            IsActive = true,
                            Name = "Information Technology",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "Corporate",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1853),
                            Description = "People Operations",
                            IsActive = true,
                            Name = "Human Resources",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "Corporate",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1855),
                            Description = "Financial Services",
                            IsActive = true,
                            Name = "Finance & Accounting",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = "Business",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1856),
                            Description = "Revenue & Growth",
                            IsActive = true,
                            Name = "Sales & Marketing",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = "Operations",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1858),
                            Description = "Facilities & Logistics",
                            IsActive = true,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Corporate",
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1859),
                            Description = "Legal Affairs",
                            IsActive = true,
                            Name = "Legal & Compliance"
                        });
                });

            modelBuilder.Entity("OnCallApi.Models.DispatchStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PhoneTreeEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneTreeEventId");

                    b.ToTable("DispatchSteps");
                });

            modelBuilder.Entity("OnCallApi.Models.DutyHourRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicableRoles")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxHoursPerPeriod")
                        .HasColumnType("int");

                    b.Property<int>("MaxShiftLengthHours")
                        .HasColumnType("int");

                    b.Property<int>("MinHoursBetweenShifts")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeriodDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DutyHourRules");
                });

            modelBuilder.Entity("OnCallApi.Models.DutyHourViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViolatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RuleId");

                    b.ToTable("DutyHourViolations");
                });

            modelBuilder.Entity("OnCallApi.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<string>("ClinicalRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Languages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("OnCallStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PagerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Presence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AzureAdObjectId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OnCallApi.Models.EscalationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ShiftId");

                    b.ToTable("EscalationEvents");
                });

            modelBuilder.Entity("OnCallApi.Models.EscalationPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EscalationTierCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxResponseMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationChannels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("EscalationPolicies");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FallbackProcedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Procedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("PhoneTrees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1356),
                            IsActive = true,
                            Name = "Code Blue — Cardiac Arrest",
                            Procedure = "Immediately call the code team and begin CPR. Bring crash cart to bedside. Assign team leads for airway, compressions, and medications.",
                            TreeType = "code-blue"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1360),
                            IsActive = true,
                            Name = "Code Red — Fire",
                            Procedure = "Evacuate immediate area. Close doors and windows. Activate fire alarm. Do not use elevators. Report to assembly point.",
                            TreeType = "code-red"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1362),
                            IsActive = true,
                            Name = "Code Green — Evacuation",
                            Procedure = "Begin horizontal evacuation to adjacent smoke compartment. Prepare for vertical evacuation if directed. Assist patients and visitors.",
                            TreeType = "code-green"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1363),
                            IsActive = true,
                            Name = "Code Silver — Active Threat",
                            Procedure = "Run. Hide. Fight. Lock all doors. Turn off lights. Stay quiet. Wait for law enforcement.",
                            TreeType = "code-silver"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1365),
                            IsActive = true,
                            Name = "Code Grey — Severe Weather",
                            Procedure = "Move patients away from windows. Close all blinds and curtains. Prepare for potential power outage.",
                            TreeType = "code-grey"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 26, 18, 47, 2, 659, DateTimeKind.Utc).AddTicks(1366),
                            IsActive = true,
                            Name = "Code Pink — Infant Abduction",
                            Procedure = "Secure all exits. Initiate lockdown. Check all persons leaving the unit. Notify security immediately.",
                            TreeType = "code-pink"
                        });
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTreeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebriefNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalIncidentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("InitiatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PhoneTreeId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseTimeSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedById");

                    b.HasIndex("PhoneTreeId");

                    b.ToTable("PhoneTreeEvents");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTreeEventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PhoneTreeEventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PhoneTreeEventId");

                    b.ToTable("PhoneTreeEventParticipants");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTreeNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PhoneTreeId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PhoneTreeId");

                    b.ToTable("PhoneTreeNodes");
                });

            modelBuilder.Entity("OnCallApi.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("OnCallApi.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("OnCallApi.Models.ShiftSwap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OriginalShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReplacementUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("OriginalShiftId");

                    b.HasIndex("ReplacementUserId");

                    b.HasIndex("RequestedById");

                    b.ToTable("ShiftSwaps");
                });

            modelBuilder.Entity("OnCallApi.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureAdGroupId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Primary hospital facility",
                            IsActive = true,
                            Name = "Main Hospital"
                        });
                });

            modelBuilder.Entity("OnCallApi.Models.TenantAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutoAssigned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AzureAdObjectId");

                    b.HasIndex("TenantId", "AzureAdObjectId")
                        .IsUnique();

                    b.ToTable("TenantAdmins");
                });

            modelBuilder.Entity("OnCallApi.Models.TimeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeOffs");
                });

            modelBuilder.Entity("OnCallApi.Models.AppSetting", b =>
                {
                    b.HasOne("OnCallApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OnCallApi.Models.CodeCallLocation", b =>
                {
                    b.HasOne("OnCallApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnCallApi.Models.Department", b =>
                {
                    b.HasOne("OnCallApi.Models.Tenant", "Tenant")
                        .WithMany("Departments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OnCallApi.Models.DispatchStep", b =>
                {
                    b.HasOne("OnCallApi.Models.PhoneTreeEvent", "PhoneTreeEvent")
                        .WithMany("DispatchSteps")
                        .HasForeignKey("PhoneTreeEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneTreeEvent");
                });

            modelBuilder.Entity("OnCallApi.Models.DutyHourRule", b =>
                {
                    b.HasOne("OnCallApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnCallApi.Models.DutyHourViolation", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnCallApi.Models.DutyHourRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("OnCallApi.Models.Employee", b =>
                {
                    b.HasOne("OnCallApi.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OnCallApi.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnCallApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OnCallApi.Models.EscalationEvent", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnCallApi.Models.EscalationPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnCallApi.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Policy");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("OnCallApi.Models.EscalationPolicy", b =>
                {
                    b.HasOne("OnCallApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTree", b =>
                {
                    b.HasOne("OnCallApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTreeEvent", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "InitiatedBy")
                        .WithMany()
                        .HasForeignKey("InitiatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OnCallApi.Models.PhoneTree", "PhoneTree")
                        .WithMany()
                        .HasForeignKey("PhoneTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatedBy");

                    b.Navigation("PhoneTree");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTreeEventParticipant", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnCallApi.Models.PhoneTreeEvent", "PhoneTreeEvent")
                        .WithMany("Participants")
                        .HasForeignKey("PhoneTreeEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PhoneTreeEvent");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTreeNode", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnCallApi.Models.PhoneTree", "PhoneTree")
                        .WithMany("Nodes")
                        .HasForeignKey("PhoneTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PhoneTree");
                });

            modelBuilder.Entity("OnCallApi.Models.Schedule", b =>
                {
                    b.HasOne("OnCallApi.Models.Department", "Department")
                        .WithMany("Schedules")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnCallApi.Models.Shift", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnCallApi.Models.Schedule", "Schedule")
                        .WithMany("Shifts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("OnCallApi.Models.ShiftSwap", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnCallApi.Models.Shift", "OriginalShift")
                        .WithMany()
                        .HasForeignKey("OriginalShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnCallApi.Models.Employee", "ReplacementUser")
                        .WithMany()
                        .HasForeignKey("ReplacementUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnCallApi.Models.Employee", "RequestedBy")
                        .WithMany("SwapRequests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("OriginalShift");

                    b.Navigation("ReplacementUser");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("OnCallApi.Models.TenantAdmin", b =>
                {
                    b.HasOne("OnCallApi.Models.Tenant", "Tenant")
                        .WithMany("TenantAdmins")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OnCallApi.Models.TimeOff", b =>
                {
                    b.HasOne("OnCallApi.Models.Employee", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnCallApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OnCallApi.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("OnCallApi.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("Shifts");

                    b.Navigation("SwapRequests");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTree", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("OnCallApi.Models.PhoneTreeEvent", b =>
                {
                    b.Navigation("DispatchSteps");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("OnCallApi.Models.Schedule", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("OnCallApi.Models.Tenant", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("TenantAdmins");
                });
#pragma warning restore 612, 618
        }
    }
}
